apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-there
  name: hello-there
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-there
  template:
    metadata:
      labels:
        app: hello-there
    spec:
      containers:
        - image: mszg/hello-there:latest
          name: hello-there
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: hello-there
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-there
  labels:
    app: hello-there
spec:
  type: NodePort
  selector:
    app: hello-there
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30066
      protocol: TCP
      name: hello
